INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('aave', 'Aave', 47, 'aave');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('algorand', 'Algorand', 19, 'algo');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('amp-token', 'Amp', 69, 'amp');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('arweave', 'Arweave', 64, 'ar');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('avalanche-2', 'Avalanche', 13, 'AVAX');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('axie-infinity', 'Axie Infinity', 26, 'axs');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('binance-usd', 'Binance USD', 18, 'busd');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('binancecoin', 'Binance Coin', 3, 'bnb');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('bitcoin', 'Bitcoin', 1, 'btc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('bitcoin-cash', 'Bitcoin Cash', 20, 'bch');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('bitcoin-cash-abc-2', 'Bitcoin Cash ABC', 62, 'bcha');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('bitcoin-cash-sv', 'Bitcoin SV', 58, 'bsv');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('bittorrent-2', 'BitTorrent', 66, 'btt');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('blockstack', 'Stacks', 68, 'stx');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('cardano', 'Cardano', 5, 'ada');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('cdai', 'cDAI', 51, 'cdai');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('celo', 'Celo', 67, 'celo');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('celsius-degree-token', 'Celsius Network', 72, 'cel');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('chainlink', 'Chainlink', 14, 'link');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('chiliz', 'Chiliz', 81, 'chz');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('compound-ether', 'cETH', 35, 'ceth');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('compound-governance-token', 'Compound', 77, 'comp');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('compound-usd-coin', 'cUSDC', 53, 'cusdc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('cosmos', 'Cosmos', 22, 'atom');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('crypto-com-chain', 'Crypto.com Coin', 43, 'cro');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('curve-dao-token', 'Curve DAO Token', 79, 'crv');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('dai', 'Dai', 30, 'dai');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('dash', 'Dash', 71, 'dash');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('decred', 'Decred', 86, 'dcr');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('dogecoin', 'Dogecoin', 9, 'doge');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('ecash', 'eCash', 54, 'xec');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('ecomi', 'ECOMI', 95, 'omi');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('elrond-erd-2', 'Elrond', 38, 'egld');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('enjincoin', 'Enjin Coin', 82, 'enj');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('eos', 'EOS', 45, 'eos');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('ethereum', 'Ethereum', 2, 'eth');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('ethereum-classic', 'Ethereum Classic', 32, 'etc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('fantom', 'Fantom', 28, 'ftm');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('filecoin', 'Filecoin', 29, 'fil');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('flow', 'Flow', 48, 'flow');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('ftx-token', 'FTX Token', 27, 'ftt');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('harmony', 'Harmony', 55, 'one');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('havven', 'Synthetix Network Token', 83, 'snx');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('hedera-hashgraph', 'Hedera', 39, 'hbar');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('helium', 'Helium', 73, 'hnt');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('holotoken', 'Holo', 84, 'hot');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('huobi-btc', 'Huobi BTC', 65, 'hbtc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('huobi-token', 'Huobi Token', 88, 'ht');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('icon', 'ICON', 91, 'icx');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('internet-computer', 'Internet Computer', 25, 'icp');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('iota', 'IOTA', 52, 'miota');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('klay-token', 'Klaytn', 49, 'klay');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('kucoin-shares', 'KuCoin Token', 93, 'kcs');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('kusama', 'Kusama', 57, 'ksm');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('leo-token', 'LEO Token', 60, 'leo');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('litecoin', 'Litecoin', 17, 'ltc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('magic-internet-money', 'Magic Internet Money', 78, 'mim');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('maker', 'Maker', 70, 'mkr');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('matic-network', 'Polygon', 21, 'matic');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('mina-protocol', 'Mina Protocol', 96, 'mina');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('monero', 'Monero', 42, 'xmr');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('near', 'Near', 36, 'near');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('nem', 'NEM', 89, 'xem');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('neo', 'NEO', 59, 'neo');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('nexo', 'NEXO', 90, 'nexo');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('okb', 'OKB', 33, 'okb');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('olympus', 'Olympus', 50, 'ohm');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('omisego', 'OMG Network', 75, 'omg');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('pancakeswap-token', 'PancakeSwap', 44, 'cake');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('polkadot', 'Polkadot', 8, 'dot');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('qtum', 'Qtum', 94, 'qtum');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('quant-network', 'Quant', 46, 'qnt');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('ravencoin', 'Ravencoin', 100, 'rvn');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('ripple', 'XRP', 7, 'xrp');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('safemoon', 'SafeMoon', 87, 'safemoon');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('shiba-inu', 'Shiba Inu', 11, 'shib');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('solana', 'Solana', 6, 'sol');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('spell-token', 'Spell Token', 80, 'spell');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('staked-ether', 'Lido Staked Ether', 37, 'steth');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('stellar', 'Stellar', 24, 'xlm');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('sushi', 'Sushi', 74, 'sushi');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('terra-luna', 'Terra', 12, 'luna');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('terrausd', 'TerraUSD', 63, 'ust');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('tether', 'Tether', 4, 'usdt');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('tezos', 'Tezos', 40, 'xtz');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('the-graph', 'The Graph', 41, 'grt');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('theta-fuel', 'Theta Fuel', 85, 'tfuel');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('theta-token', 'Theta Network', 34, 'theta');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('thorchain', 'THORChain', 56, 'rune');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('tron', 'TRON', 31, 'trx');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('true-usd', 'TrueUSD', 98, 'tusd');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('uniswap', 'Uniswap', 16, 'uni');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('usd-coin', 'USD Coin', 10, 'usdc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('vechain', 'VeChain', 23, 'vet');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('waves', 'Waves', 61, 'waves');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('wrapped-bitcoin', 'Wrapped Bitcoin', 15, 'wbtc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('xdce-crowd-sale', 'XDC Network', 97, 'xdc');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('yearn-finance', 'yearn.finance', 99, 'yfi');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('zcash', 'Zcash', 76, 'zec');
INSERT INTO modocripto.tab_cripto (ID_Cripto, Nome_Cripto, MKT_Cap_Rank, Symbol) VALUES ('zilliqa', 'Zilliqa', 92, 'zil');